language: android
jdk:
  - oraclejdk8
android:
  components:
      - tools
      - platform-tools
      - build-tools-25.0.1
      - android-25
      - extra-google-m2repository
      - extra-android-m2repository

script:
  - ./gradlew clean
  - ./gradlew dualcache-library:check -Ptravis
